### ISSUE TITLE
[bug] <title>why doesn't my dApp connect mobile metamask app from mobile browser

### ISSUE THREAD

**Issue by sniper365** [rainbow-me/rainbowkit#1293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

1.0.5

### Current Behavior

This is my index.tsx

```
import * as React from "react"
import { ColorModeScript } from "@chakra-ui/react"
import { createRoot } from 'react-dom/client';
import { App } from "./App"
import './index.css';
import merge from 'lodash.merge';
import { getDefaultWallets, RainbowKitProvider, darkTheme, Theme } from '@rainbow-me/rainbowkit';
import { configureChains, createConfig, WagmiConfig } from 'wagmi';
import { goerli, mainnet } from 'wagmi/chains';
import { publicProvider } from 'wagmi/providers/public';
import '@rainbow-me/rainbowkit/styles.css'

const { chains, publicClient, webSocketPublicClient } = configureChains(
  [
    mainnet,
  ],
  [publicProvider()]
);

const { connectors } = getDefaultWallets({
  appName: 'bitoro',
  projectId: '2023-5',
  chains,
});

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
  webSocketPublicClient,
});

const myTheme = merge(darkTheme({
  borderRadius: 'small'
}), {
  colors: {
    accentColor: '#194a8c',  //bitoro.600
    connectButtonBackground: '#00204c',
    modalBackground: '#002559',  //bitoro.1000
    modalText: 'white',
    actionButtonSecondaryBackground: '#6686b2',  //bitoro.300
  },
  fonts: {
    body: '20px',
  },
});

const container = document.getElementById("root")
const root = createRoot(container!)
root.render(
  // <React.StrictMode>
  <>
    <WagmiConfig config={wagmiConfig}>
      <RainbowKitProvider
        chains={chains}
        theme={myTheme}
      >
        <ColorModeScript />
        <App />
      </RainbowKitProvider>
    </WagmiConfig>
  </>
  // </React.StrictMode>,
)
```

It's working on browser but not working on mobile.

Please help me. I searched many many times but not helpful. Thank you

**Comment by DanielSinclair** [comment]
@sniper365 Can you share a CodeSandbox and step by step test path? Have been unable to replicate any of your previous issues.

**Comment by sniper365** [comment]
@DanielSinclair 

Here is sandbox

https://codesandbox.io/p/github/sniper365/bitoro-codesandbox-test/master?file=/src/components/bitoroHeader/index.tsx:1,1&workspaceId=db2815ed-51c7-4310-949f-75c1d42b0e6b

Please review it?

**Comment by DanielSinclair** [comment]
@sniper365 Am encountering an error with the CodeSandbox:
<img width="516" alt="Screenshot 2023-06-13 at 10 04 05 PM" src="https://github.com/rainbow-me/rainbowkit/assets/4412473/2a6727f0-8b62-48ff-b778-f4ccb9ffbe54">

**Comment by sniper365** [comment]
@DanielSinclair 
Please check it out now. I fixed error.

**Comment by DanielSinclair** [comment]
@sniper365 Still seeing errors. Can you create as minimal of a reproducible example as possible and share the test path?
