### ISSUE TITLE
[bug] Modal open state (`connectModalOpen`) does not get reset after sign-in with RainbowKitAuthenticationProvider

### ISSUE THREAD

**Issue by alexandergitter** [rainbow-me/rainbowkit#1503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.3

### wagmi Version

1.4.13

### Current Behavior

After signing in with a custom authentication adapter (via `RainbowKitAuthenticationProvider`), the state of the connect modal (`connectModalOpen`) does not get reset to `false`.

### Expected Behavior

After sign-in, when all modals are closed, `connectModalOpen` should be `false`.

### Steps To Reproduce

Make sure you can run the example app (in `packages/example`) as described in https://github.com/rainbow-me/rainbowkit/blob/main/.github/CONTRIBUTING.md#development-environment.

1. In the example app, replace the `RainbowKitApp` component function (in `packages/example/pages/_app.tsx`) with the following two component functions and make sure to add any missing imports:

```typescript
function ConnectComponent() {
  const { connectModalOpen } = useConnectModal();

  return (
    <div>
      <ConnectButton />
      <div style={{marginTop: "20px"}}>{`connectModalOpen: ${connectModalOpen}`}</div>
    </div>
  );
}

function RainbowKitApp({
  Component,
  pageProps,
}: AppProps<{
  session: Session;
}>) {
  const [authenticationStatus, setAuthenticationStatus] = useState<AuthenticationStatus>('unauthenticated');

  const authenticationAdapter = createAuthenticationAdapter({
    getNonce: async () => {
      return '1234567890';
    },

    createMessage: ({ nonce, address, chainId }) => {
      return new SiweMessage({
        domain: window.location.host,
        address,
        statement: 'Sign in with Ethereum to the app.',
        uri: window.location.origin,
        version: '1',
        chainId,
        nonce,
      });
    },

    getMessageBody: () => {
      return 'Test';
    },

    verify: async () => {
      setAuthenticationStatus('authenticated');

      return true;
    },

    signOut: async () => {
      setAuthenticationStatus('unauthenticated');
    },
  });

  return (
    <RainbowKitAuthenticationProvider
      adapter={authenticationAdapter}
      status={authenticationStatus}
    >
      <RainbowKitProvider chains={chains}>
        <ConnectComponent />
      </RainbowKitProvider>
    </RainbowKitAuthenticationProvider>
  );
}
```
2. Run the example app
3. Observe the "connectModalOpen: false" text I added to the document, which is bound to `connectModalOpen`.
4. Click the connect button and sign in with your Wallet (I'm using Metamask for my tests).
5. Observe how `connectModalOpen` says "true", even though all modals are closed after the sign-in.

### Anything else?

Here's an example screencast:
[Screencast from 05.09.2023 08:31:34.webm](https://github.com/rainbow-me/rainbowkit/assets/816758/08a033d0-3370-4b64-b150-75a9db5bb42e)

**Comment by alexandergitter** [comment]
On further investigation, it turns out that the modal closes when the `status` passed into `RainbowKitAuthenticationProvider` changes:
```jsx
<RainbowKitAuthenticationProvider adapter={authenticationAdapter} status={authenticationStatus}>
  ...
</RainbowKitAuthenticationProvider>
```
That doesn't change the modal state though. I'm assuming the modal element is getting removed somewhere based on this change, without going through the `ModalContext` functions intended for this.

One way to fix it is to add a call to `onClose` after verification in `SignIn.tsx` (before the return): https://github.com/rainbow-me/rainbowkit/blob/4bd6ef76566ecd907a56182fdc3dc8d08a7b9fee/packages/rainbowkit/src/components/SignIn/SignIn.tsx#L98-L99

**Comment by DanielSinclair** [comment]
@alexandergitter I believe this issue is now resolved because of a separate fix. Can you test with RainbowKit `1.0.12`? I've also added modal statuses to our example dApp to test this flow with #1541. Feel free to reference the example dApp deployment [here](https://rainbowkit-example-git-daniel-modal-hooks-d-511d44-rainbowdotme.vercel.app/).

**Comment by alexandergitter** [comment]
@DanielSinclair This issue still exists in Rainbowkit 1.2.1 and can be reproduced the way I described it above.

**Comment by alexandergitter** [comment]
@DanielSinclair I updated (and simplified) my reproduction instructions. The problem still exists in version 1.3.3, can you please re-open this issue?
Than you!

**Comment by KosmosKey** [comment]
@alexandergitter I can reproduce this issue on my end. Can you try testing it in this [preview link](https://rainbowkit-example-p1d6ncuf4-rainbowdotme.vercel.app/) and let me know if it works now ? It should set the `connectModalOpen` state back to `false` after a successful login

**Comment by alexandergitter** [comment]
Looks good to me, thank you!
