### ISSUE TITLE
[bug] react-remove-scroll-bar: cannot calculate scrollbar size because it is removed

### ISSUE THREAD

**Issue by shrugs** [rainbow-me/rainbowkit#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.5

### wagmi Version

0.6.0

### Current Behavior

We've disabled body scrolling on our page with `overflow: hidden`, since it's a full-page app.

When rainbowkit attempts to hide the scroll bar to show a modal, the react-remove-scroll lib throws an error, which clogs the console (though otherwise does not seem to affect behavior)

`react-remove-scroll-bar: cannot calculate scrollbar size because it is removed (overflow:hidden on body`

<img width="696" alt="image" src="https://user-images.githubusercontent.com/1535001/182486796-c65e9f6c-8b4a-4ecb-848e-db4ce00351b6.png">

### Expected Behavior

Should gracefully ignore that body cannot be scrolled, since that's the behavior it would like anyway.

### Steps To Reproduce

add `overflow: hidden` to body

**Comment by markdalgleish** [comment]
Thanks for reporting this! I've opened a PR with a fix.

**Comment by markdalgleish** [comment]
This is fixed in [RainbowKit v0.4.6](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%400.4.6).

**Comment by ethjcdenton** [comment]
Still seeing this same issue, because #639 only considers `body` having the hidden attribute. Maybe there's a way to pass in this flag into the dialog?

cc @markdalgleish

**Comment by shrugs** [comment]
Also still seeing this on 0.5 unfortunately, even though that check in #639 looks like it'll work correctly in practice
