### ISSUE TITLE
[bug] Don't show login pop-up on MM Mobile

### ISSUE THREAD

**Issue by LeoClairet05** [rainbow-me/rainbowkit#746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.5.2

### wagmi Version

0.6.0

### Current Behavior

https://user-images.githubusercontent.com/56917328/189865243-bd357cb8-c53e-42b1-b96c-d27de2638aa4.MP4

I try to connect MetaMask on mobile from Safari like on your website where it works fine. But when I try with my React app or with your react example, it doesn't work as you can see on the video (where I'm using your react example).

Any idea? I've tried different things but nothing seems to solve the problem 😕 

Your example react-app deployed on my heroku : https://wagmi-test.herokuapp.com/

### Expected Behavior

Open MM mobile connect popup

![IMG_66AC08532A66-1](https://user-images.githubusercontent.com/56917328/189866229-f681cc19-2e64-4748-a249-39ed5d00db31.jpeg)

### Steps To Reproduce

Clone [with-create-react-app](https://github.com/rainbow-me/rainbowkit/tree/main/examples/with-create-react-app) 

Start and try to connect using Safari on IOS

**Comment by LeoClairet05** [comment]
Solution : https://github.com/rainbow-me/rainbowkit/issues/420

**Comment by tuminzee** [comment]
@LeoClairet05 will there be support for vite as well?

**Comment by tuminzee** [comment]
> Solution found thanks to : #420
> 
> Why it's not working with React (without NextJS)?
> 
> It's not working since Webpack 5.0, Buffer is not installed by default anymore so it creates an issue with WalletConnect (Used when you try to connect with MetaMask from another browser than the integrated one in MetaMask mobile app). **⚠️ Make sure your react app use https & not http, or it'll not work.**
> 
> I've created a public repository that you can clone to have a working react app that integrates Rainbowkit, Wagmi without NextJS -> https://github.com/LeoClairet05/wagmi-rainbowkit-react-template
> 
> On my template Wagmi is configured to connect on custom chains Fuji & Avalanche.
> 
> To make it works on your own project you can follow these steps:
> 
> Install "react-app-rewired" -> https://www.npmjs.com/package/react-app-rewired
> 
> Change your package.json scripts as following:
> 
> `"scripts": { "start": "HTTPS=true react-app-rewired start", "build": "GENERATE_SOURCEMAP=false react-app-rewired build", "test": "react-app-rewired test", "eject": "react-scripts eject" }`
> 
> and add the following devDependencies in your package.json: `"devDependencies": { "assert": "^2.0.0", "buffer": "^6.0.3", "crypto-browserify": "^3.12.0", "https-browserify": "^1.0.0", "os-browserify": "^0.3.0", "process": "^0.11.10", "react-app-rewired": "^2.2.1", "stream-browserify": "^3.0.0", "stream-http": "^3.2.0", "url": "^0.11.0" }`
> 
> create a new file in your directory named "config-overrides.js" with the following content:
> 
> ` const webpack = require('webpack');
> 
> module.exports = function override(config) { const fallback = config.resolve.fallback || {}; Object.assign(fallback, { "crypto": require.resolve("crypto-browserify"), "stream": require.resolve("stream-browserify"), "assert": require.resolve("assert"), "http": require.resolve("stream-http"), "https": require.resolve("https-browserify"), "os": require.resolve("os-browserify"), "url": require.resolve("url") }) config.ignoreWarnings = [/Failed to parse source map/]; config.resolve.fallback = fallback; config.plugins = (config.plugins || []).concat([ new webpack.ProvidePlugin({ process: 'process/browser', Buffer: ['buffer', 'Buffer'] }) ]) return config; } `

Is there a way to undo this process, I added this code and I was able to run it on https,
But even after deleting all the dependencies, removing the node_modules, and reinstalling the packages, 
It still goes back to pointing to **https**

**Comment by LeoClairet05** [comment]
Yes, just remove the HTTPS=true from the package.json in "scripts":{"starts"

**Comment by LeoClairet05** [comment]
> 

I don't know ^^

**Comment by tuminzee** [comment]
It was weird to see this unexpected behaviour because even with react-scripts start it was pointing to _https_
😆 😭 I will try different approaches @LeoClairet05 
thank you for your help

**Comment by graphicstone** [comment]
Is this issue fixed in the latest update or do I need to do the above work around, because when I followed the above steps above by @LeoClairet05, I got connection not secure on my localhost.

**Comment by tuminzee** [comment]
> Is this issue fixed in the latest update or do I need to do the above work around, because when I followed the above steps above by @LeoClairet05, I got connection not secure on my localhost. 

Local host will not allow you to connect to unsecured connection by default 
If you are using Chrome, you'd have to explicitly visit the page by bypass the warning page. 

Hope this helps

**Comment by graphicstone** [comment]
Yeah that issue is resolved. Thanks for the help. Now it's working as expected.

**Comment by sshmaxime** [comment]
After struggling for a bit, I finally found the solution for `Vite`.
I was having another error along the line of: `Unhandled Promise Rejection: ReferenceError: Cannot access uninitialized variable.` 
For anyone having this issue with `Vite` you need to populate the window with something called Buffer. I have no idea why it works but it works for me.

Just go in your `index.html` add a script in your <head></head> like so:
```html
 <script type="module">
      import { Buffer } from "buffer";
      window.Buffer = Buffer;
</script>
```

Hope that helps someone :)

**Comment by abdullah-txfusion** [comment]
@sshmaxime This isn't working now, still getting the `Uncaught ReferenceError: Buffer is not defined`

**Comment by issa-me-sush** [comment]
if yall are still facing problems in 2024 , w rainbowkit v 1.0> ,  I struggled quite a bit and found a config that magically fixes teh mobile connect issue lol :

next.config.js file :

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack: config => {
    config.resolve.fallback = { fs: false, net: false, tls: false };
    return config;
  },
};

module.exports = nextConfig;
```

**Comment by vishalguptax** [comment]
Can anyone tell me how to fix it for React Vite + TS app?

**Comment by dreamdev2427** [comment]
How to apply this solution to my Next.js project?

**Comment by dreamdev2427** [comment]
I am using "@rainbow-me/rainbowkit": "^2.0.2" , but it doesn't work on mobile devices.

**Comment by simondevz** [comment]
same here @luckydev2528. Did you find a work around?
